[project]
name = "dicom-navigator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pydicom>=3.0.1",
    "requests>=2.32.5",
    "textual>=6.8.0",
]
